ifndef::backend-docbook5,backend-docbook45[:imagesdir: ../../..]
[id='cloudcamelk-practice']
= Integrating Cloud-native services using Camel K

In this exercise, you will develop a Camel K integration for a book publishing company.

The company requires you to expose the book manuscripts in a REST endpoint.
You must deploy the integration application to Red{nbsp}Hat OpenShift.

== Outcomes

You should be able to:

[compact]
* Deploy an integration in the cloud by using Camel K.
* Leverage Camel K development mode to receive feedback while developing.

The solution files for this exercise are in the `+AD221-apps+` repository, within the `+cloud-camelk/solutions+` directory.

== Prerequisites

To perform this exercise, ensure you have the following:

[compact]
* The `+AD221-apps+` repository cloned in your workstation.
* Access to a configured and running OpenShift cluster.
* The OpenShift CLI (`+oc+`) installed.
* The Camel K CLI (`+kamel+`) installed.
// https://downloads.apache.org/camel/camel-k/1.6.1/  <-- kamel CLI required for RH Integration - Camel K 1.6

From your workspace directory, use the `+lab+` command to start this exercise.

[subs=+quotes]
----
[student@workstation AD221]$ *lab start cloud-camelk*
----

The `+lab+` command copies the exercise files from the `+~/AD221/AD221-apps/cloud-camelk/apps+` directory, into the `+~/AD221/cloud-camelk+` directory.
It also verifies the connection to the OpenShift shared cluster, and creates a project to deploy the application.

[role='Checklist']
== Instructions

1) Navigate to the `+~/AD221/cloud-camelk+` directory, open the project with your editor of choice, and examine the code.

// -----------------------------------------------------------------------------

2) Run the Camel K application in develop mode by using the `+kamel run ManuscriptsApi.java --dev+` command.
Wait for the deployment to finish.

[subs=+quotes]
----
_...output omitted..._
... [io.quarkus] (main) camel-k-integration 1.6.3 ... started in 2.707s. Listening on: http://0.0.0.0:8080
_...output omitted..._
----

[IMPORTANT]
====
The initial Camel K deployment might take a few minutes to finish.
Subsequent deployments should be faster.
====

// -----------------------------------------------------------------------------

3) Open a new terminal and use the `+oc get route+` command to get the route assigned to the Camel K application.

[subs=+quotes]
----
[student@workstation cloud-camelk]$ *oc get route -o \
jsonpath="{'http://'}{..spec.host}{'/manuscripts'}{'\n'}"*
----

Open your web browser, and navigate to the REST endpoint.
Verify that the application throws an internal server error because the integration has some missing parts.

// -----------------------------------------------------------------------------

4) Open the `+ManuscriptsApi+` class, and add the following dependencies:

[compact]
* `+camel-quarkus-jackson+`
* `+camel-quarkus-jacksonxml+`

The dependency imports must look like the following:

[subs=+quotes]
----
// TODO: Add Camel K imports
`// camel-k: dependency=camel-quarkus-jacksonxml
// camel-k: dependency=camel-quarkus-jackson`
----

// -----------------------------------------------------------------------------

5) Add the following runtime resources to the integration pod:

[compact]
* `+./data/manuscripts/book-01.xml+`
* `+./data/manuscripts/book-02.xml+`

Camel K copies your local runtime resources into the `+/etc/camel/resources+` directory of the integration pod container.

The resource declarations must look like the following:

[subs=+quotes]
----
// TODO: Add Camel K resources
`// camel-k: resource=file:./data/manuscripts/book-01.xml
// camel-k: resource=file:./data/manuscripts/book-02.xml`
----

// -----------------------------------------------------------------------------

6) Create a route to store all the books assigned to the editors into an in-memory storage.

The route must collect all the books located in the `+file:/etc/camel/resources+` endpoint, and unmarshal the data to convert it to the JSON format.
Process the JSON data, and store it as an `+Object+` type in the `+inMemoryBooks+` variable.
You must set `+manuscripts+` as the route ID, and use the `+noop+` option in the consumer endpoint.

[NOTE]
====
You can use the `+log+` method in the route to track the progress of the file processing.
====

The route must look like the following:

[subs=+quotes]
----
// TODO: Add a route to store all books in the local variable
`from("file:/etc/camel/resources?noop=true")
    .routeId("manuscripts")
    .log("Processing file: ${header.CamelFileName}")
    .unmarshal().jacksonxml()
    .process().body(Object.class, (Consumer<Object>) inMemoryBooks::add);`
----

// -----------------------------------------------------------------------------

7) Save the changes to trigger a new deployment of the Camel K application, and wait for the integration to process the book files.

[subs=+quotes]
----
_...output omitted..._
... Processing file: book-01.xml
... Processing file: book-02.xml
----

[IMPORTANT]
====
The Camel K development mode command might hang if you introduce compilation errors.
If this happens, then stop and restart the command.
====

// -----------------------------------------------------------------------------

8) Return to the browser, and reload the Camel K application URL.
Notice that the application returns a JSON response with the information about two books.

// -----------------------------------------------------------------------------

== Finish

Stop the Camel K application, return to your workspace directory, and use the `+lab+` command to complete this exercise.
This is important to ensure that resources from previous exercises do not impact upcoming exercises.

[subs=+quotes]
----
[student@workstation AD221]$ *lab finish cloud-camelk*
----
